name: crazy_button
description: Flutter widget to provide your widget a wiggle animation you can pass any widget to the Crazy Button and it will give it a shake animation
version: 1.0.3
homepage: https://github.com/Rohit-joshi-i/crazy_button

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
